=== alberto-ionut-toscariu/PW-Laborator1/continut/persoane.dtd
<!ELEMENT persoane (persoana)+>
<!ELEMENT persoana (nume,prenume,varsta,adresa,experienta)>
<!ATTLIST persoana id CDATA #REQUIRED>
<!ELEMENT nume (#PCDATA)>
<!ELEMENT prenume (#PCDATA)>
<!ELEMENT varsta (#PCDATA)>
<!ELEMENT adresa (strada,numar,localitate,judet,tara)>
<!ELEMENT strada (#PCDATA)>
<!ELEMENT numar (#PCDATA)>
<!ELEMENT localitate (#PCDATA)>
<!ELEMENT judet (#PCDATA)>
<!ELEMENT tara (#PCDATA)>
<!ELEMENT experienta (job-actual,studii)>
<!ELEMENT job-actual (#PCDATA)>
<!ELEMENT studii (#PCDATA)>

=== alberto-ionut-toscariu/PW-Laborator1/continut/persoane.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE persoane SYSTEM "persoane.dtd">
<persoane>
    <persoana id="1">
        <nume>Popescu</nume>
        <prenume>Ion</prenume>
        <varsta>23</varsta>
        <adresa> 
          <strada> Pompierilor </strada>
          <numar>5B </numar>
          <localitate>Ipotesti</localitate>
          <judet>Suceava</judet>
          <tara>Romania</tara>
        </adresa>
        <experienta>
          <job-actual> taximetrist</job-actual>
          <studii> liceale </studii>
        </experienta>
    </persoana>
      <persoana id="2">
        <nume>Georgescu</nume>
        <prenume>Geta</prenume>
        <varsta>21</varsta>
        <adresa>
          <strada> Bucuriei </strada>
          <numar>1A </numar>
          <localitate>Mileanca</localitate>
          <judet>Botosani</judet>
          <tara>Romania</tara>
        </adresa>
        <experienta>
          <job-actual> programator</job-actual>
          <studii> liceale </studii>
        </experienta>
    </persoana>
      <persoana id="3">
        <nume>Horodincu</nume>
        <prenume>Monica</prenume>
        <varsta>45</varsta>
        <adresa> 
          <strada> Mozartstrase </strada>
          <numar>91052 </numar>
          <localitate>Erlagen</localitate>
          <judet>Nuremberg</judet>
          <tara>Germania</tara>
        </adresa>
        <experienta>
          <job-actual> inginer</job-actual>
          <studii> superioare </studii>
        </experienta>

    </persoana>
    
</persoane>
